name: Building AMI

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Building Machine Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Debug AWS Region Secret
        run: echo "AWS_REGION is set to '${{ secrets.AWS_REGION }}'"

      - name: Install Packer
        uses: hashicorp/setup-packer@main

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y unzip jq

      - name: Building Application Artifact
        run: |
          mkdir -p build
          zip -r build/webapp.zip ./*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-artifact
          path: build/webapp.zip

      - name: Setting Environment Variables
        run: |
          echo "DATABASE_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.DB_NAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DATABASE_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          cat .env

      - name: Packer Initialization
        working-directory: ami
        run: packer init .

      - name: Validate Packer Template
        working-directory: ami
        run: packer validate .

      - name: Build AMI with Packer
        working-directory: ami
        env:
          PACKER_DB_NAME: ${{ secrets.DB_NAME }}
          PACKER_DB_USER: ${{ secrets.DB_USER }}
          PACKER_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: packer build .
