name: Packer CI

on:
  pull_request:
    branches:
      - main  
jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@main

    - name: Configure GCP Credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDS }}

    - name: Setting GCP SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Setting GCP Access Key
      working-directory: ami
      run: | 
        echo '${{ secrets.GCP_CREDS }}' >> .gcp-key.json

    - name: Setting Environment Variables
      run: |
          echo "DATABASE_NAME=${{ secrets.DB_NAME }}" > .env
          echo "DATABASE_USERNAME=${{ secrets.DB_USER }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DATABASE_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          cat .env

    - name: Build Application Artifact
      run: |
          mkdir -p build
          zip -r build/webapp.zip ./* .env # Include .env in the zip file
          ls -l build/webapp.zip # Debug: Verify the artifact is created

    - name: Copy Artifact and .env to AMI Directory
      run: |
          mkdir -p ami
          cp build/webapp.zip ami/webapp.zip
          cp .env ami/.env # Copy .env to the ami directory
          ls -l ami # Debug: Verify the contents of the ami directory
    - name: Run Initialization
      working-directory: ami
      run: packer init .

    - name: Run Packer fmt
      working-directory: ami
      run: |
        packer fmt -check .
      continue-on-error: false
      id: packer-fmt

    - name: Run Packer validate
      working-directory: ami
      env:
        AMI_USER: ${{ secrets.AWS_DEMO }}
      run: |
        packer validate .
      continue-on-error: false
      id: packer-validate

    - name: Fail workflow if fmt or validate failed
      run: |
        if [[ "${{ steps.packer-fmt.outcome }}" == "failure" ]]; then
          echo "Packer fmt failed. Please format the template before merging.";
          exit 1;
        fi
        if [[ "${{ steps.packer-validate.outcome }}" == "failure" ]]; then
          echo "Packer validate failed. Please fix the template before merging.";
          exit 1;
        fi
