name: Packer CI

on:
  pull_request:
    branches:
      - main  
jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@main

    - name: Setting Environment Variables
      run: |
          echo "DATABASE_NAME=${{ secrets.DB_NAME }}" > .env
          echo "DATABASE_USERNAME=${{ secrets.DB_USER }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DATABASE_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          cat .env

    - name: Build Application Artifact
      run: |
          mkdir -p build
          zip -r build/webapp.zip ./*
          ls -l build/webapp.zip # Debug: Verify the artifact is created

    - name: Copy Artifact to AMI Directory
      run: |
          mkdir -p ami
          cp build/webapp.zip ami/webapp.zip
          ls -l ami/webapp.zip # Debug: Verify the artifact is copied

    - name: Run Initialization
      working-directory: ami
      run: packer init .

    - name: Run Packer fmt
      working-directory: ami
      run: |
        packer fmt -check .
      continue-on-error: false
      id: packer-fmt

    - name: Run Packer validate
      working-directory: ami
      run: |
        packer validate .
      continue-on-error: false
      id: packer-validate

    - name: Fail workflow if fmt or validate failed
      run: |
        if [[ "${{ steps.packer-fmt.outcome }}" == "failure" ]]; then
          echo "Packer fmt failed. Please format the template before merging.";
          exit 1;
        fi
        if [[ "${{ steps.packer-validate.outcome }}" == "failure" ]]; then
          echo "Packer validate failed. Please fix the template before merging.";
          exit 1;
        fi
